version: '3.9'
services:
  backend:
    build: ./server
    ports:
      - "1243:1243"
    volumes:
      - ./server:/usr/src/app
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "3421:3421"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge