version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "1243:1243"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - client

  client:
    build: ./client
    ports:
      - "3421:3421"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/usr/src/app