version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3421:3421"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./server
    ports:
      - "1243:1243"
