POST  http://localhost:1243/shop/checkout
Content-Type: application/json

{
    "member": "A1111",
    "cart": {
        "0":{
            "id": 1,
            "quantity": 5
        },
        "1":{
            "id": 2,
            "quantity": 3
        }
    }
}